export const NICHE_PRESETS: string[] = [
  'dental clinic',
  'стоматологія',
  'private clinic',
  'beauty salon',
  'барбершоп',
  'restaurant',
  'coffee shop',
  'fitness gym',
  'yoga studio',
  'автосервіс',
  'автомийка',
  'veterinary clinic',
  'law firm',
  'юрист',
  'accounting services',
  'real estate agency',
  'агентство нерухомості',
  'construction company',
  'ремонт квартир',
  'cleaning company',
  'клiнінг',
  'hotel',
  'дитячий садок',
  'школа',
  'tutoring services',
  'фотограф',
  'event agency',
  'кейтеринг',
  'flower shop',
  'зоомагазин',
  'optika',
  'меблі на замовлення',
  'window installation',
  'solar panels installation',
  'marketing agency',
  'IT company',
];

export const LOCATION_PRESETS: string[] = [
  'Kyiv, Ukraine',
  'Львів, Україна',
  'Одеса, Україна',
  'Харків, Україна',
  'Дніпро, Україна',
  'Вінниця, Україна',
  'Запоріжжя, Україна',
  'Івано-Франківськ, Україна',
  'Тернопіль, Україна',
  'Чернівці, Україна',
  'Ужгород, Україна',
  'Warsaw, Poland',
  'Krakow, Poland',
  'Berlin, Germany',
  'Munich, Germany',
  'Prague, Czech Republic',
  'London, UK',
  'New York, USA',
  'Los Angeles, USA',
  'Toronto, Canada',
];

export const KEYWORDS_PRESETS: string[] = [
  'booking',
  'онлайн запис',
  'online order',
  'delivery',
  'prices',
  'ціни',
  'contacts',
  'instagram',
];

export const NICHE_SUGGESTIONS = Array.from(new Set(NICHE_PRESETS.map((n) => n.trim()))).filter(Boolean);
export const LOCATION_SUGGESTIONS = Array.from(new Set(LOCATION_PRESETS.map((l) => l.trim()))).filter(Boolean);
