import './setup';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {requestWithSession} from '@/lib/assistant/session-request';
function fixture(statuses:number[],refreshFails=false){let refreshes=0;const tokens:string[]=[];const bodies:string[]=[];const auth={getSession:async()=>({data:{session:{access_token:'old-synthetic'}},error:null}),refreshSession:async()=>{refreshes++;return {data:{session:refreshFails?null:{access_token:'fresh-synthetic'}},error:refreshFails?new Error('expired'):null};}};const fetcher=(async(_input,init)=>{tokens.push(new Headers(init?.headers).get('Authorization')!);bodies.push(String(init?.body));const status=statuses.shift()!;return Response.json(status===200?{kind:'text',text:'ok'}:{kind:'error',error:{code:'unavailable',message:'Потрібно повторно увійти в CRM'}},{status});}) as typeof fetch;return {auth,fetcher,tokens,bodies,get refreshes(){return refreshes;}};}
test('assistant refreshes rejected session once and retries with fresh token and same request',async()=>{const f=fixture([401,200]);assert.deepEqual(await requestWithSession(f.auth,{text:'balance'},undefined,f.fetcher),{kind:'text',text:'ok'});assert.equal(f.refreshes,1);assert.deepEqual(f.tokens,['Bearer old-synthetic','Bearer fresh-synthetic']);assert.equal(f.bodies[0],f.bodies[1]);});
test('assistant second auth rejection stops retrying and explains CRM login, not provider outage',async()=>{const f=fixture([401,401]);const r=await requestWithSession(f.auth,{},undefined,f.fetcher) as {error:{hint:string}};assert.equal(f.refreshes,1);assert.equal(f.tokens.length,2);assert.match(r.error.hint,/увійди в CRM/);assert.ok(!r.error.hint.includes('провайдер'));});
test('failed refresh preserves auth rejection and never sends another request',async()=>{const f=fixture([401],true);await requestWithSession(f.auth,{},undefined,f.fetcher);assert.equal(f.tokens.length,1);assert.equal(f.refreshes,1);});
test('success and non-auth failures do not refresh or duplicate requests',async()=>{for(const status of [200,429,500]){const f=fixture([status]);await requestWithSession(f.auth,{},undefined,f.fetcher);assert.equal(f.tokens.length,1);assert.equal(f.refreshes,0);}});
